services:
  - type: server
    directory: server
    name: server
    host: test.com
  - type: client
    directory: client
    name: client
  - type: client
    directory: client2
    name: client2
  - type: db
    directory: server
    name: mongo
    storages:
      - userdata
      - otherdata